name: texter
favicon: null
layout_spectrum: 0.34162772889249027
typography_spectrum: 0.43062291922979057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7831967957317829
  lightness: 0.3119448518846184
  saturation: 0.21438999916426837
  rhythmicContrast: 0.5621131814550608
purpose: []
